import Head from "next/head";
import React from "react";
import axios from "axios";
import ProductCard from "../components/ProductCard";
import ProductSkeleton from "../components/ProductSkeleton";

export interface IPost {
  _id: number;
  category: string;
  description: string;
  images: string[];
  name: string;
  user: {
    name: string;
  };
}

export default function Home() {
    const [posts, setPosts] = React.useState<IPost[]>([]);
    const [isLoading, setIsLoading] = React.useState(true);

    React.useEffect(() => {
      getProducts();
    }, []);

    const getProducts = async () => {
      setIsLoading(true);
      try {
        const { data } = await axios.get("https://isp-trade.onrender.com/posts");
        setPosts(data);
        setIsLoading(false);
        console.log(data);
      } catch (error) {
        console.log(error);
      }
    };

    return (
      <>
        <Head>
          <title>ISP1 Trade</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <div className='content'>
          {isLoading ? [...Array(10)].map(() => <ProductSkeleton/>) :
              posts.map((post, i) => (
                  <ProductCard key={i} product={post}/>
          ))}
        </div>
      </>
    );
}
