import Head from "next/head";
import React from "react";
import ProductCard from "../components/ProductCard";
import { useSelector } from "react-redux";
import { RootState } from "../redux/store";
import { IPost } from ".";

export default function Home() {
  const { findItems } = useSelector((state: RootState) => state.search);

  return (
    <>
      <Head>
        <title>Hagi. Clo - Результаты поиска</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='content'>
        {findItems.length === 0 && (
          <div style={{ fontSize: "24px" }}>
            По вашему запросу ничего не найдено :(
          </div>
        )}
        {findItems.map((product: IPost, i: number) => (
          <ProductCard key={i} product={product} />
        ))}
      </div>
    </>
  );
}
